version: '3.4'

services:
  sampleproject:
    image: portafolio-2024
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3300:3000
